### ISSUE TITLE
Display steam account names / nicknames in launcher

### ISSUE THREAD

**Issue by jhoule86** [Karmastic/Launcher#16]
To help resolve the questions about "who is using this (borrowed) account?" the launcher could display the in-use steam account somewhere.

Bonus: add the info on the in-progress game list to advertise usernames to the group

| Name | account | Game |
| ------ | --------- | ------- |
Carl | steam: CarlIsGreat9000 | Element TD 2

Extra bonus: the game list has one entry per running game, with the name + accounts nested under the game name

**Comment by Karmastic** [comment]
If the steam account includes the account's SteamID, we can use the web API to get their current username.
Unclear what's returned if profile is set to Private (this is my own so it might work regardless).
eg:
https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=API_KEY_HERE&steamids=76561197971228690.
Returns:
{
  "response": {
    "players": [
      {
        "steamid": "76561197971228690",
        "communityvisibilitystate": 3,
        "profilestate": 1,
        "personaname": "Karmastic",
        "profileurl": "https://steamcommunity.com/profiles/76561197971228690/",
        "avatar": "https://avatars.steamstatic.com/2ab7e48f9c7cc6ffe0c8e16b60367a617c33196f.jpg",
        "avatarmedium": "https://avatars.steamstatic.com/2ab7e48f9c7cc6ffe0c8e16b60367a617c33196f_medium.jpg",
        "avatarfull": "https://avatars.steamstatic.com/2ab7e48f9c7cc6ffe0c8e16b60367a617c33196f_full.jpg",
        "avatarhash": "2ab7e48f9c7cc6ffe0c8e16b60367a617c33196f",
        "lastlogoff": 1725751137,
        "personastate": 1,
        "realname": "Karmastic",
        "primaryclanid": "103582791465976924",
        "timecreated": 1101623429,
        "personastateflags": 0,
        "loccountrycode": "US",
        "locstatecode": "NH"
      }
    ]
  }
}

Current game launched through launcher is obviously known and can be shared.

**Comment by jhoule86** [comment]
If I recall correctly, the client always says `launching G with steam account A`, so the cheap option in my head was to use the account that shows up in that modal.

**Comment by Karmastic** [comment]
Plumbed in communicating launcher type and account (eg steam name) used for running games.  Currently just added to launcher's listview.

![image](https://github.com/user-attachments/assets/56b6bb8b-3194-4107-93a1-daa532e9570f)

Karmastic/K05#25
